### ISSUE TITLE
DOC: how to load variables into vars.yml and use in tasks

### ISSUE THREAD

**Issue by hirundinidae** [hexadecimalDinosaur/htv8#12]
Using jinja render, take variables (to be submitted in the form) and render the vars-template.yml file to vars.yml, and the playbooks should be setup to import variables from the vars file. 

I'm not sure if variables can be loaded into the inventory file, so the jinja rendering will also have to happen there. Will revisit if I have time. 
```
# this only works in the playbook 
  tasks:
    - name: load vars 
      ansible.builtin.include_vars: 
        file: vars.yml
    - name: Print message
      ansible.builtin.debug:
        msg: Hello {{ test_var }}
```
run ansible.py, which generates the inventory and vars file from templates directory. Now the playbooks have the required files to run.
